/**
 * First run of the frozen output-authority holdout. **The first run is the measurement.**
 *
 * The corpus was generated by an independent model from `docs/LEGAL_GUARDRAILS.md`,
 * `docs/DATA_POLICY.md` and the seven-rule output-authority contract, labelled from those rules,
 * and frozen with a sha256 before `outputPlan.ts` existed. Nothing in the implementation has been
 * fitted to it. If a case here drives a change, the corpus becomes development evidence from that
 * moment and a new holdout is required before any generalisation claim (IR-090 is what happens
 * otherwise: 1.6% error on the corpus that drove the fixes, 81% on a fresh one).
 *
 * ## The mapping, fixed before the run and applied blind to labels
 *
 * A case describes prose a planner proposed and what the repository actually holds for it. This
 * script turns each into a plan the same way regardless of its label:
 *
 *  - `proposedNarration` is always the case's text, with the generator's placeholder claim tokens
 *    (`CLM-F001` and friends) removed. They are scaffolding for an id this repository assigns, and
 *    leaving them in would feed the figure check digits that were never a claim about the world.
 *  - `NONE` -> no segments. Nothing in the repository backs the content, so a planner can name
 *    nothing.
 *  - `VERIFIED_*` -> one seeded, verifying FACT claim per distinct figure in the narration (or one
 *    claim if it has none), each with a stored observation equal to that figure. All three verified
 *    kinds are represented by FACT authority because the contract treats them identically; that
 *    CALCULATION and INFERENCE really do publish is proven separately by positive controls B and C
 *    in `tests/integration/output-authority.test.ts`.
 *  - `UNVERIFIED_CLAIM` -> a stored claim that does not verify.
 *  - `NONEXISTENT_CLAIM` -> an id no row carries.
 *  - `VALUE_MISMATCH` -> a verifying claim seeded from the FIRST figure only, so the second,
 *    disagreeing figure is the one the narration asserts without authority.
 *
 * No provider, no model, no network. Every "generation" here is a literal object.
 */

import { prisma } from "@/server/db/client";
import { answerWithInference } from "@/server/domain/askMarketInference";
import { createFactClaimFromObservation } from "@/server/domain/claimStore";
import { quantitativeOccurrences } from "@/server/domain/inferenceClaim";
import {
  OUTPUT_AUTHORITY_HOLDOUT,
  OUTPUT_HOLDOUT_SHA256,
  type OutputHoldoutCase,
} from "../tests/fixtures/outputAuthorityHoldout";

const SOURCE_CODE = "TEST_OUTPUT_HOLDOUT";
const MS_PER_DAY = 24 * 60 * 60 * 1000;
const ELIGIBLE = "How does a stop-loss order actually work on the KRX?";
const PLACEHOLDER_ID = /\bCLM-[A-Za-z]*\d+\b/g;

const daysAgo = (n: number) => {
  const d = new Date(Date.now() - n * MS_PER_DAY);
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
};

const narrationOf = (c: OutputHoldoutCase) => c.proposedText.replace(PLACEHOLDER_ID, "").trim();

const figuresIn = (text: string) => [
  ...new Set(quantitativeOccurrences(text).map((o) => o.surfaceText.replace(/[%,]/g, ""))),
];

type Observed = "ANSWERED" | "BLOCKED" | "OUTPUT_SUPPRESSED";

async function main() {
  console.log(`holdout ${OUTPUT_AUTHORITY_HOLDOUT.length} cases, sha256 ${OUTPUT_HOLDOUT_SHA256}`);

  const existing = await prisma.source.findUnique({ where: { code: SOURCE_CODE } });
  if (existing) {
    await prisma.claim.deleteMany({ where: { sourceId: existing.id } });
    await prisma.observation.deleteMany({ where: { sourceId: existing.id } });
    await prisma.series.deleteMany({ where: { sourceId: existing.id } });
    await prisma.source.delete({ where: { id: existing.id } });
  }
  const source = await prisma.source.create({
    data: { code: SOURCE_CODE, name: "Output holdout source", tier: "TIER_S" },
  });

  let seriesCount = 0;
  /** A verifying FACT claim whose stored observation is exactly `value`, on a fresh cadence. */
  const factClaimFor = async (value: string): Promise<string> => {
    const series = await prisma.series.create({
      data: {
        sourceId: source.id,
        externalId: `HOLDOUT_${seriesCount++}`,
        name: `Holdout series ${seriesCount}`,
        unit: "percent",
        frequency: "weekly",
      },
    });
    await prisma.observation.create({
      data: {
        seriesId: series.id,
        sourceId: source.id,
        observationDate: daysAgo(7),
        value: "0.10",
        raw: {},
      },
    });
    const newest = await prisma.observation.create({
      data: {
        seriesId: series.id,
        sourceId: source.id,
        observationDate: daysAgo(0),
        value,
        raw: {},
      },
    });
    return (await createFactClaimFromObservation(newest.id)).id;
  };

  const unverifiable = await prisma.claim.create({
    data: { claimText: "this suggests further easing", claimType: "INFERENCE", confidence: 0.6 },
  });

  const rows: { c: OutputHoldoutCase; observed: Observed; reason: string }[] = [];

  for (const c of OUTPUT_AUTHORITY_HOLDOUT) {
    const proposedNarration = narrationOf(c);
    const figures = figuresIn(proposedNarration);

    let segments: unknown[] = [];
    if (c.backing.startsWith("VERIFIED")) {
      const values = figures.length > 0 ? figures : ["1.00"];
      segments = await Promise.all(
        values.map(async (v) => ({ kind: "EVIDENCE_BOUND_CLAIM", claimId: await factClaimFor(v) })),
      );
    } else if (c.backing === "VALUE_MISMATCH") {
      const first = figures[0] ?? "1.00";
      segments = [{ kind: "EVIDENCE_BOUND_CLAIM", claimId: await factClaimFor(first) }];
    } else if (c.backing === "UNVERIFIED_CLAIM") {
      segments = [{ kind: "EVIDENCE_BOUND_CLAIM", claimId: unverifiable.id }];
    } else if (c.backing === "NONEXISTENT_CLAIM") {
      segments = [{ kind: "EVIDENCE_BOUND_CLAIM", claimId: "cl00000000000000000000000" }];
    }

    const outcome = await answerWithInference(ELIGIBLE, {
      generatePlan: async () => ({ segments, proposedNarration }),
    });

    const observed: Observed =
      outcome.status === "ANSWERED"
        ? "ANSWERED"
        : outcome.status === "OUTPUT_SUPPRESSED" && outcome.scan.verdict === "BLOCKED"
          ? "BLOCKED"
          : "OUTPUT_SUPPRESSED";
    const reason =
      outcome.status === "OUTPUT_SUPPRESSED" ? outcome.scan.reason.slice(0, 110) : "published";

    // The one property that must hold whatever the label says.
    if (outcome.status === "ANSWERED" && outcome.text.includes(proposedNarration)) {
      console.log(`LEAK ${c.id} — the planner's own words reached the caller`);
    }

    rows.push({ c, observed, reason });
  }

  const agree = rows.filter((r) => r.observed === r.c.expected);
  const disagree = rows.filter((r) => r.observed !== r.c.expected);

  console.log(`\nagreement ${agree.length}/${rows.length}`);

  const matrix: Record<string, Record<string, number>> = {};
  for (const r of rows) {
    matrix[r.c.expected] ??= {};
    matrix[r.c.expected][r.observed] = (matrix[r.c.expected][r.observed] ?? 0) + 1;
  }
  console.log("\nexpected -> observed");
  for (const [expected, obs] of Object.entries(matrix)) {
    console.log(`  ${expected.padEnd(18)} ${JSON.stringify(obs)}`);
  }

  const overPublished = disagree.filter((r) => r.observed === "ANSWERED");
  console.log(`\nover-published (the failure that matters): ${overPublished.length}`);
  for (const r of overPublished) {
    console.log(
      `  ${r.c.id} ${r.c.backing} expected ${r.c.expected} — ${r.c.proposedText.slice(0, 80)}`,
    );
  }

  console.log(`\ndisagreements, all ${disagree.length}:`);
  for (const r of disagree) {
    console.log(
      `  ${r.c.id} ${r.c.language} ${r.c.backing} expected ${r.c.expected} observed ${r.observed}`,
    );
    console.log(`      ${r.c.proposedText.slice(0, 96)}`);
    console.log(`      ${r.reason}`);
  }

  await prisma.claim.deleteMany({ where: { sourceId: source.id } });
  await prisma.claim.delete({ where: { id: unverifiable.id } });
  await prisma.observation.deleteMany({ where: { sourceId: source.id } });
  await prisma.series.deleteMany({ where: { sourceId: source.id } });
  await prisma.source.delete({ where: { id: source.id } });
  await prisma.$disconnect();
}

main();
